name: build

on: 
  push:
    paths: 
      - build/**
      - .github/workflows/build.yml

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
          ANDROID_NDK=$(pwd)/android-ndk-r15c
      - name: Build
        run: |
          cd build
          ./make_android_lua54.sh
          ./make_android_lua53.sh
          sudo apt install gcc-multilib
        # ./make_android_luajit_arm64.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua54/**/*
          name: plugin_lua54
      - name: Upload53
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua53/**/*
          name: plugin_lua53   
      # - name: UploadJit
      #   uses: actions/upload-artifact@v2
      #   with:
      #     path: ./build/plugin_luajit/**/*
      #     name: plugin_luajit
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd build
          cd luac
          ./make_unix_lua54.sh
          ./make_unix.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build/luac/luac_lua54/**/*
          name: luac_lua54
      - name: Upload53
        uses: actions/upload-artifact@v2
        with:
          path: ./build/luac/luac_lua53/**/*
          name: luac_lua53
  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd build
          ./make_ios_lua54.sh
          ./make_ios_lua53.sh
        # ./make_ios_luajit.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua54/**/*
          name: plugin_lua54
      - name: Upload53
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua53/**/*
          name: plugin_lua53   
      # - name: UploadJit
      #   uses: actions/upload-artifact@v2
      #   with:
      #     path: ./build/plugin_luajit/**/*
      #     name: plugin_luajit
  osx:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd build
          ./make_osx_lua54.sh
          ./make_osx_lua53.sh
          ./make_osx_editor_lua53.sh
          ./make_osx_editor_lua54.sh
        # ./make_osx_luajit.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua54/**/*
          name: plugin_lua54
      - name: Upload53
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua53/**/*
          name: plugin_lua53   
      # - name: UploadJit
      #   uses: actions/upload-artifact@v2
      #   with:
      #     path: ./build/plugin_luajit/**/*
      #     name: plugin_luajit  
  windows:
    runs-on: windows-2016

    steps:
      - uses: actions/checkout@v2
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.0.2
      
      - name: Build
        run: |
          cd build
          .\make_win_lua54.bat
          .\make_win_lua54_editor.bat
          .\make_win32_lua53.bat
          .\make_win64_lua53.bat
          .\make_win32_editor_lua53.bat
          .\make_win64_editor_lua53.bat
          cd luac
          .\make_win64.bat
          .\make_win64_lua54.bat
        # .\make_uwp.bat
        # .\make_uwp_lua54.bat
        # .\make_win32_luajit.bat
        # .\make_win64_luajit.bat
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua54/**/*
          name: plugin_lua54
      - name: Upload53
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua53/**/*
          name: plugin_lua53
      - name: Upload_luac_53
        uses: actions/upload-artifact@v2
        with:
          path: ./build/luac/luac_lua53/**/*
          name: luac_lua53  
      - name: Upload_luac_54
        uses: actions/upload-artifact@v2
        with:
          path: ./build/luac/luac_lua54/**/*
          name: luac_lua54
      # - name: UploadJit
      #   uses: actions/upload-artifact@v2
      #   with:
      #     path: ./build/plugin_luajit/**/*
      #     name: plugin_luajit
    

   
